name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller chuckstaroidsv5.spec
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChuckSTARoids-Windows
        path: dist/ChuckSTARoids_v5.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller chuckstaroidsv5_mac.spec
    
    - name: Create DMG
      run: |
        # Install create-dmg
        brew install create-dmg
        
        # Create DMG
        create-dmg \
          --volname "ChuckSTARoids v5" \
          --volicon "xwing.ico" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "ChuckSTARoids_v5.app" 175 120 \
          --hide-extension "ChuckSTARoids_v5.app" \
          --app-drop-link 425 120 \
          "ChuckSTARoids_v5.dmg" \
          "dist/"
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChuckSTARoids-macOS
        path: ChuckSTARoids_v5.dmg

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: ChuckSTARoids-Windows
        path: ./release-assets
    
    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: ChuckSTARoids-macOS
        path: ./release-assets
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release-assets/ChuckSTARoids_v5.exe
          ./release-assets/ChuckSTARoids_v5.dmg
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
